name: CI

on:
  push:
    branches:
      - main
      - master
      - '**'
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer
          extensions: mbstring

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Validate composer.json
        run: composer validate --strict

      - name: Lint (php-cs-fixer dry run)
        run: composer format

      - name: Static analysis
        run: composer analyse

      - name: Unit tests
        run: composer test:unit

  integration:
    runs-on: ubuntu-latest
    needs: quality
    env:
      MAILRIFY_API_KEY: ${{ secrets.MAILRIFY_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: mbstring

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Integration tests
        env:
          MAILRIFY_API_KEY: ${{ secrets.MAILRIFY_API_KEY }}
          MAILRIFY_INTEGRATION_FROM=: ${{ secrets.MAILRIFY_INTEGRATION_FROM }}
          MAILRIFY_INTEGRATION_TO: ${{ secrets.MAILRIFY_INTEGRATION_TO }}
        run: composer test:integration
